# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "zeriyoshi blog"
weight = 1

[ja]
languageName = "Japanese"
languagedirection = "ltr"
title = "ぜりブログ"
weight = 1
