baseurl = "//zeriyoshi.github.io/"
languageCode = "ja-jp"
paginate = 5
title = "ぜりブログ"
defaultContentLanguage = "ja"
hasCJKLanguage = true
disqusShortname = "zeriyoshi-blog"
relativeURLs = true
canonifyURLs = true
